import { createServiceLogger } from '../lib/logger';
const logger = createServiceLogger('SmartFilter');

import type { Express, Request, Response } from "express";
import { requireMaster } from "../middleware/auth";
import { smartFilter } from "../services/smart-filter";

export async function registerSmartFilterRoutes(app: Express): Promise<void> {

  app.post("/api/synergy/filter/apply", requireMaster, async (req: Request, res: Response) => {
    try {
      const { subject, from, body, platform, contact } = req.body;
      const result = smartFilter.applyFilters({ subject, from, body, platform, contact });
      res.json(result);
    } catch (error) {
      res.status(500).json({ error: "过滤失败" });
    }
  });

  app.get("/api/synergy/filter/rules", requireMaster, async (req: Request, res: Response) => {
    try {
      const rules = smartFilter.getRules();
      res.json({ rules });
    } catch (error) {
      res.status(500).json({ error: "获取规则失败" });
    }
  });

  app.post("/api/synergy/filter/rules", requireMaster, async (req: Request, res: Response) => {
    try {
      const { name, type, conditions, action, category, enabled, isAutoGenerated } = req.body;
      
      if (!name || !type || !conditions || !action) {
        return res.status(400).json({ error: "请提供name, type, conditions和action" });
      }
      
      const rule = smartFilter.addRule({
        name,
        type,
        conditions,
        action,
        category: category || 'notification',
        enabled: enabled !== false,
        isAutoGenerated: isAutoGenerated || false,
      });
      
      res.json({ success: true, rule });
    } catch (error) {
      res.status(500).json({ error: "创建规则失败" });
    }
  });

  app.put("/api/synergy/filter/rules/:id", requireMaster, async (req: Request, res: Response) => {
    try {
      const { id } = req.params;
      const updates = req.body;
      
      const rule = smartFilter.updateRule(id, updates);
      if (!rule) {
        return res.status(404).json({ error: "规则不存在" });
      }
      
      res.json({ success: true, rule });
    } catch (error) {
      res.status(500).json({ error: "更新规则失败" });
    }
  });

  app.delete("/api/synergy/filter/rules/:id", requireMaster, async (req: Request, res: Response) => {
    try {
      const { id } = req.params;
      const deleted = smartFilter.deleteRule(id);
      res.json({ success: deleted });
    } catch (error) {
      res.status(500).json({ error: "删除规则失败" });
    }
  });

  app.post("/api/synergy/learning/event", requireMaster, async (req: Request, res: Response) => {
    try {
      const { type, itemId, itemType, metadata } = req.body;
      
      if (!type || !itemId || !itemType) {
        return res.status(400).json({ error: "请提供type, itemId和itemType" });
      }
      
      smartFilter.recordLearningEvent({
        type,
        itemId,
        itemType,
        metadata: metadata || {},
        timestamp: new Date(),
      });
      
      res.json({ success: true });
    } catch (error) {
      res.status(500).json({ error: "记录学习事件失败" });
    }
  });

  app.get("/api/synergy/preferences", requireMaster, async (req: Request, res: Response) => {
    try {
      const prefs = smartFilter.getPreferences('master');
      res.json(prefs || {});
    } catch (error) {
      res.status(500).json({ error: "获取偏好失败" });
    }
  });

  app.put("/api/synergy/preferences", requireMaster, async (req: Request, res: Response) => {
    try {
      const updates = req.body;
      const prefs = smartFilter.updatePreferences('master', updates);
      res.json({ success: true, preferences: prefs });
    } catch (error) {
      res.status(500).json({ error: "更新偏好失败" });
    }
  });

  app.get("/api/synergy/filter/statistics", requireMaster, async (req: Request, res: Response) => {
    try {
      const stats = smartFilter.getStatistics();
      res.json(stats);
    } catch (error) {
      res.status(500).json({ error: "获取统计失败" });
    }
  });
}
