/**
 * 小智 Smart Filter Service - 智能过滤与学习
 * Project Synergy (协同协议) - 噪音过滤与偏好学习
 * 
 * 功能：
 * 1. 噪音过滤 - 学习用户偏好，过滤无关信息
 * 2. 优先级学习 - 根据用户行为调整信息优先级
 * 3. 个性化规则 - 自动生成过滤规则
 * 
 * 版权：陈先生出品 · cj6168888@Gmail.com
 */

export type FilterCategory = 'promotion' | 'newsletter' | 'notification' | 'social' | 'work' | 'personal' | 'spam' | 'important';

export interface FilterRule {
  id: string;
  name: string;
  type: 'keyword' | 'sender' | 'pattern' | 'ai';
  conditions: FilterCondition[];
  action: 'hide' | 'low_priority' | 'archive' | 'highlight' | 'notify';
  category: FilterCategory;
  enabled: boolean;
  hitCount: number;
  createdAt: Date;
  lastHitAt: Date | null;
  isAutoGenerated: boolean;
}

export interface FilterCondition {
  field: 'subject' | 'from' | 'body' | 'platform' | 'contact';
  operator: 'contains' | 'equals' | 'startsWith' | 'endsWith' | 'regex' | 'notContains';
  value: string;
  caseSensitive: boolean;
}

export interface UserPreference {
  userId: string;
  preferredContacts: string[];
  mutedContacts: string[];
  importantKeywords: string[];
  noiseKeywords: string[];
  quietHours: { start: string; end: string } | null;
  priorityPlatforms: string[];
  updatedAt: Date;
}

export interface FilterResult {
  passed: boolean;
  action: FilterRule['action'];
  matchedRules: string[];
  suggestedCategory: FilterCategory;
  priorityScore: number;
}

export interface LearningEvent {
  type: 'read' | 'reply' | 'archive' | 'delete' | 'star' | 'mute';
  itemId: string;
  itemType: 'email' | 'message' | 'notification';
  metadata: Record<string, any>;
  timestamp: Date;
}

class SmartFilterService {
  private rules: Map<string, FilterRule> = new Map();
  private preferences: Map<string, UserPreference> = new Map();
  private learningEvents: LearningEvent[] = [];

  private defaultRules: Partial<FilterRule>[] = [
    {
      name: '广告邮件过滤',
      type: 'keyword',
      conditions: [
        { field: 'subject', operator: 'contains', value: '促销', caseSensitive: false },
        { field: 'subject', operator: 'contains', value: '优惠', caseSensitive: false },
        { field: 'subject', operator: 'contains', value: '限时', caseSensitive: false },
      ],
      action: 'low_priority',
      category: 'promotion',
    },
    {
      name: '订阅通讯过滤',
      type: 'keyword',
      conditions: [
        { field: 'subject', operator: 'contains', value: 'newsletter', caseSensitive: false },
        { field: 'subject', operator: 'contains', value: '周报', caseSensitive: false },
        { field: 'from', operator: 'contains', value: 'noreply', caseSensitive: false },
      ],
      action: 'archive',
      category: 'newsletter',
    },
    {
      name: '重要邮件高亮',
      type: 'keyword',
      conditions: [
        { field: 'subject', operator: 'contains', value: '发票', caseSensitive: false },
        { field: 'subject', operator: 'contains', value: '合同', caseSensitive: false },
        { field: 'subject', operator: 'contains', value: '付款', caseSensitive: false },
      ],
      action: 'highlight',
      category: 'important',
    },
  ];

  constructor() {
    this.initializeDefaultRules();
  }

  private initializeDefaultRules(): void {
    this.defaultRules.forEach((rule, index) => {
      const id = `default_${index}`;
      this.rules.set(id, {
        id,
        name: rule.name || '',
        type: rule.type || 'keyword',
        conditions: rule.conditions || [],
        action: rule.action || 'low_priority',
        category: rule.category || 'notification',
        enabled: true,
        hitCount: 0,
        createdAt: new Date(),
        lastHitAt: null,
        isAutoGenerated: true,
      });
    });
  }

  applyFilters(
    content: { subject?: string; from?: string; body?: string; platform?: string; contact?: string }
  ): FilterResult {
    const matchedRules: string[] = [];
    const result = { action: 'notify' as FilterRule['action'], priorityScore: 50 };
    let suggestedCategory: FilterCategory = 'personal';

    this.rules.forEach((rule, id) => {
      if (!rule.enabled) return;

      const matches = this.checkRuleConditions(rule, content);
      if (matches) {
        matchedRules.push(id);
        rule.hitCount++;
        rule.lastHitAt = new Date();

        if (rule.action === 'hide') {
          result.action = 'hide';
          result.priorityScore = 0;
        } else if (rule.action === 'highlight' && result.action !== 'hide') {
          result.action = 'highlight';
          result.priorityScore = 100;
        } else if (rule.action === 'low_priority' && result.priorityScore > 20) {
          result.priorityScore = 20;
        }

        suggestedCategory = rule.category;
      }
    });

    return {
      passed: result.action !== 'hide',
      action: result.action,
      matchedRules,
      suggestedCategory,
      priorityScore: result.priorityScore,
    };
  }

  private checkRuleConditions(rule: FilterRule, content: Record<string, any>): boolean {
    if (rule.conditions.length === 0) return false;

    return rule.conditions.some(condition => {
      const value = content[condition.field] || '';
      const searchValue = condition.caseSensitive ? condition.value : condition.value.toLowerCase();
      const targetValue = condition.caseSensitive ? value : value.toLowerCase();

      switch (condition.operator) {
        case 'contains':
          return targetValue.includes(searchValue);
        case 'equals':
          return targetValue === searchValue;
        case 'startsWith':
          return targetValue.startsWith(searchValue);
        case 'endsWith':
          return targetValue.endsWith(searchValue);
        case 'notContains':
          return !targetValue.includes(searchValue);
        case 'regex':
          try {
            const regex = new RegExp(condition.value, condition.caseSensitive ? '' : 'i');
            return regex.test(value);
          } catch {
            return false;
          }
        default:
          return false;
      }
    });
  }

  recordLearningEvent(event: LearningEvent): void {
    this.learningEvents.push(event);
    
    if (this.learningEvents.length > 1000) {
      this.learningEvents.splice(0, 500);
    }

    this.updatePreferencesFromEvent(event);
  }

  private updatePreferencesFromEvent(event: LearningEvent): void {
    const userId = 'master';
    let prefs = this.preferences.get(userId);
    
    if (!prefs) {
      prefs = {
        userId,
        preferredContacts: [],
        mutedContacts: [],
        importantKeywords: [],
        noiseKeywords: [],
        quietHours: null,
        priorityPlatforms: [],
        updatedAt: new Date(),
      };
      this.preferences.set(userId, prefs);
    }

    const contact = event.metadata.contact || event.metadata.from;
    
    if (event.type === 'reply' || event.type === 'star') {
      if (contact && !prefs.preferredContacts.includes(contact)) {
        prefs.preferredContacts.push(contact);
        prefs.mutedContacts = prefs.mutedContacts.filter(c => c !== contact);
      }
    } else if (event.type === 'mute' || event.type === 'delete') {
      if (contact && !prefs.mutedContacts.includes(contact)) {
        prefs.mutedContacts.push(contact);
        prefs.preferredContacts = prefs.preferredContacts.filter(c => c !== contact);
      }
    }

    prefs.updatedAt = new Date();
  }

  addRule(rule: Omit<FilterRule, 'id' | 'hitCount' | 'createdAt' | 'lastHitAt'>): FilterRule {
    const id = `rule_${Date.now()}`;
    const newRule: FilterRule = {
      ...rule,
      id,
      hitCount: 0,
      createdAt: new Date(),
      lastHitAt: null,
    };
    this.rules.set(id, newRule);
    return newRule;
  }

  updateRule(id: string, updates: Partial<FilterRule>): FilterRule | null {
    const rule = this.rules.get(id);
    if (!rule) return null;
    
    const updated = { ...rule, ...updates };
    this.rules.set(id, updated);
    return updated;
  }

  deleteRule(id: string): boolean {
    return this.rules.delete(id);
  }

  getRules(): FilterRule[] {
    return Array.from(this.rules.values());
  }

  getPreferences(userId: string = 'master'): UserPreference | undefined {
    return this.preferences.get(userId);
  }

  updatePreferences(userId: string, updates: Partial<UserPreference>): UserPreference {
    let prefs = this.preferences.get(userId);
    if (!prefs) {
      prefs = {
        userId,
        preferredContacts: [],
        mutedContacts: [],
        importantKeywords: [],
        noiseKeywords: [],
        quietHours: null,
        priorityPlatforms: [],
        updatedAt: new Date(),
      };
    }
    const updated = { ...prefs, ...updates, updatedAt: new Date() };
    this.preferences.set(userId, updated);
    return updated;
  }

  getStatistics(): {
    totalRules: number;
    activeRules: number;
    totalHits: number;
    topRules: Array<{ id: string; name: string; hitCount: number }>;
  } {
    const rules = Array.from(this.rules.values());
    const totalHits = rules.reduce((sum, r) => sum + r.hitCount, 0);
    const topRules = [...rules]
      .sort((a, b) => b.hitCount - a.hitCount)
      .slice(0, 5)
      .map(r => ({ id: r.id, name: r.name, hitCount: r.hitCount }));

    return {
      totalRules: rules.length,
      activeRules: rules.filter(r => r.enabled).length,
      totalHits,
      topRules,
    };
  }
}

export const smartFilter = new SmartFilterService();
