/**
 * 任务执行追踪服务
 * Task Execution Tracker Service
 * 
 * 功能：
 * 1. 任务分配与确认
 * 2. 执行追踪 - 定期检查进度
 * 3. 遇到困难时自动寻找解决方案
 * 4. 主动汇报进度
 * 5. 完成后总结反馈
 */

import { createServiceLogger } from '../lib/logger';
const logger = createServiceLogger('TaskExecutionTracker');

export type TaskStatus = 
  | 'ASSIGNED'      // 已分配，待确认
  | 'CONFIRMED'     // 已确认，开始执行
  | 'IN_PROGRESS'   // 执行中
  | 'BLOCKED'       // 遇到困难
  | 'RESOLVING'     // 正在解决困难
  | 'COMPLETED'     // 已完成
  | 'CANCELLED';    // 已取消

export type TaskPriority = 'LOW' | 'NORMAL' | 'HIGH' | 'URGENT';

export interface TaskExecution {
  id: string;
  userId: string;
  
  // 任务信息
  title: string;
  description: string;
  originalRequest: string;  // 用户原始请求
  
  // 状态
  status: TaskStatus;
  priority: TaskPriority;
  
  // 执行信息
  assignedAt: Date;
  startedAt?: Date;
  completedAt?: Date;
  deadline?: Date;
  
  // 进度
  progress: number;        // 0-100
  progressNotes: string[];  // 进度记录
  
  // 遇到的问题
  blockers: BlockedIssue[];
  
  // 解决方案
  solutions: TaskSolution[];
  
  // 汇报记录
  reports: ProgressReport[];
  
  // 最终结果
  result?: string;
  resultSummary?: string;
  
  // 元数据
  createdAt: Date;
  updatedAt: Date;
}

export interface BlockedIssue {
  id: string;
  description: string;
  encounteredAt: Date;
  resolvedAt?: Date;
  isResolved: boolean;
  attempts: string[];  // 尝试过的解决方法
}

export interface TaskSolution {
  id: string;
  description: string;
  attemptedAt: Date;
  succeeded: boolean;
  result?: string;
}

export interface ProgressReport {
  id: string;
  generatedAt: Date;
  progress: number;
  status: TaskStatus;
  message: string;
  isAutoGenerated: boolean;
}

class TaskExecutionTracker {
  private tasks: Map<string, TaskExecution> = new Map();
  private userTasks: Map<string, Set<string>> = new Map();  // userId -> taskIds
  private checkInterval: NodeJS.Timeout | null = null;
  private isRunning = false;
  
  private readonly CHECK_INTERVAL = 30 * 60 * 1000;  // 每30分钟检查一次
  private readonly REPORT_INTERVAL = 60 * 60 * 1000; // 每小时汇报一次
  private readonly MAX_BLOCK_ATTEMPTS = 5;           // 遇到困难最多尝试5次

  constructor() {
    logger.info('[TaskExecutionTracker] 任务执行追踪服务已创建');
  }

  /**
   * 启动服务
   */
  start(): void {
    if (this.isRunning) return;
    
    this.isRunning = true;
    this.checkInterval = setInterval(() => {
      this.checkAndProcessTasks().catch(err => {
        logger.error({ err }, '任务检查失败');
      });
    }, this.CHECK_INTERVAL);
    
    logger.info('[TaskExecutionTracker] 任务执行追踪服务已启动');
  }

  /**
   * 停止服务
   */
  stop(): void {
    if (this.checkInterval) {
      clearInterval(this.checkInterval);
      this.checkInterval = null;
    }
    this.isRunning = false;
    logger.info('[TaskExecutionTracker] 任务执行追踪服务已停止');
  }

  /**
   * 分配新任务
   */
  assignTask(
    userId: string,
    title: string,
    description: string,
    originalRequest: string,
    priority: TaskPriority = 'NORMAL',
    deadline?: Date
  ): TaskExecution {
    const task: TaskExecution = {
      id: `task_${Date.now()}_${Math.random().toString(36).slice(2, 9)}`,
      userId,
      title,
      description,
      originalRequest,
      status: 'ASSIGNED',
      priority,
      assignedAt: new Date(),
      deadline,
      progress: 0,
      progressNotes: [],
      blockers: [],
      solutions: [],
      reports: [],
      createdAt: new Date(),
      updatedAt: new Date(),
    };

    this.tasks.set(task.id, task);
    
    if (!this.userTasks.has(userId)) {
      this.userTasks.set(userId, new Set());
    }
    this.userTasks.get(userId)!.add(task.id);

    logger.info({ taskId: task.id, userId, title }, '新任务已分配');
    
    return task;
  }

  /**
   * 确认任务开始执行
   */
  confirmTask(taskId: string): TaskExecution | null {
    const task = this.tasks.get(taskId);
    if (!task) return null;

    task.status = 'CONFIRMED';
    task.startedAt = new Date();
    task.progress = 5;
    task.progressNotes.push(`[${new Date().toLocaleString()}] 任务已确认，开始执行`);
    task.updatedAt = new Date();

    logger.info({ taskId }, '任务已确认');
    return task;
  }

  /**
   * 开始执行任务
   */
  startTask(taskId: string): TaskExecution | null {
    const task = this.tasks.get(taskId);
    if (!task) return null;

    task.status = 'IN_PROGRESS';
    if (!task.startedAt) {
      task.startedAt = new Date();
    }
    task.progress = 10;
    task.progressNotes.push(`[${new Date().toLocaleString()}] 开始执行任务`);
    task.updatedAt = new Date();

    logger.info({ taskId }, '任务开始执行');
    return task;
  }

  /**
   * 更新任务进度
   */
  updateProgress(
    taskId: string, 
    progress: number, 
    note: string
  ): TaskExecution | null {
    const task = this.tasks.get(taskId);
    if (!task) return null;

    task.progress = Math.min(100, Math.max(0, progress));
    task.progressNotes.push(`[${new Date().toLocaleString()}] ${note}`);
    task.updatedAt = new Date();

    if (task.progress === 100) {
      task.status = 'COMPLETED';
      task.completedAt = new Date();
      task.progressNotes.push(`[${new Date().toLocaleString()}] 任务已完成`);
    }

    return task;
  }

  /**
   * 遇到困难
   */
  encounterBlocker(taskId: string, issue: string): TaskExecution | null {
    const task = this.tasks.get(taskId);
    if (!task) return null;

    const blocker: BlockedIssue = {
      id: `block_${Date.now()}`,
      description: issue,
      encounteredAt: new Date(),
      isResolved: false,
      attempts: [],
    };

    task.blockers.push(blocker);
    task.status = 'BLOCKED';
    task.updatedAt = new Date();

    logger.info({ taskId, issue }, '任务遇到困难');
    
    return task;
  }

  /**
   * 记录尝试的解决方案
   */
  attemptSolution(
    taskId: string,
    blockerId: string,
    solution: string
  ): TaskExecution | null {
    const task = this.tasks.get(taskId);
    if (!task) return null;

    const blocker = task.blockers.find(b => b.id === blockerId);
    if (!blocker) return null;

    blocker.attempts.push(solution);
    
    const taskSolution: TaskSolution = {
      id: `sol_${Date.now()}`,
      description: solution,
      attemptedAt: new Date(),
      succeeded: false,
    };
    
    task.solutions.push(taskSolution);
    task.status = 'RESOLVING';
    task.updatedAt = new Date();

    return task;
  }

  /**
   * 标记困难已解决
   */
  resolveBlocker(taskId: string, blockerId: string, result?: string): TaskExecution | null {
    const task = this.tasks.get(taskId);
    if (!task) return null;

    const blocker = task.blockers.find(b => b.id === blockerId);
    if (!blocker) return null;

    blocker.resolvedAt = new Date();
    blocker.isResolved = true;
    
    const taskSolution = task.solutions.find(s => s.description === blocker.attempts[blocker.attempts.length - 1]);
    if (taskSolution) {
      taskSolution.succeeded = true;
      taskSolution.result = result;
    }

    // 检查是否还有其他未解决的困难
    const hasOtherBlockers = task.blockers.some(b => !b.isResolved);
    if (!hasOtherBlockers) {
      task.status = 'IN_PROGRESS';
      task.progressNotes.push(`[${new Date().toLocaleString()}] 困难已解决，继续执行`);
    }

    task.updatedAt = new Date();
    
    logger.info({ taskId, blockerId }, '困难已解决');
    return task;
  }

  /**
   * 完成任务
   */
  completeTask(taskId: string, result: string, summary?: string): TaskExecution | null {
    const task = this.tasks.get(taskId);
    if (!task) return null;

    task.status = 'COMPLETED';
    task.progress = 100;
    task.completedAt = new Date();
    task.result = result;
    task.resultSummary = summary || this.generateSummary(task);
    task.progressNotes.push(`[${new Date().toLocaleString()}] 任务已完成: ${result}`);
    task.updatedAt = new Date();

    logger.info({ taskId, result }, '任务已完成');
    return task;
  }

  /**
   * 取消任务
   */
  cancelTask(taskId: string, reason?: string): TaskExecution | null {
    const task = this.tasks.get(taskId);
    if (!task) return null;

    task.status = 'CANCELLED';
    if (reason) {
      task.progressNotes.push(`[${new Date().toLocaleString()}] 任务已取消: ${reason}`);
    }
    task.updatedAt = new Date();

    logger.info({ taskId, reason }, '任务已取消');
    return task;
  }

  /**
   * 获取用户的所有任务
   */
  getUserTasks(userId: string): TaskExecution[] {
    const taskIds = this.userTasks.get(userId);
    if (!taskIds) return [];

    return Array.from(taskIds)
      .map(id => this.tasks.get(id))
      .filter((t): t is TaskExecution => t !== undefined)
      .sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime());
  }

  /**
   * 获取活跃任务
   */
  getActiveTasks(userId: string): TaskExecution[] {
    return this.getUserTasks(userId).filter(t => 
      ['ASSIGNED', 'CONFIRMED', 'IN_PROGRESS', 'BLOCKED', 'RESOLVING'].includes(t.status)
    );
  }

  /**
   * 获取任务详情
   */
  getTask(taskId: string): TaskExecution | null {
    return this.tasks.get(taskId) || null;
  }

  /**
   * 生成进度汇报
   */
  generateProgressReport(taskId: string): ProgressReport | null {
    const task = this.tasks.get(taskId);
    if (!task) return null;

    let message = '';
    
    switch (task.status) {
      case 'ASSIGNED':
        message = `任务「${task.title}」已收到，正在准备开始执行～`;
        break;
      case 'CONFIRMED':
        message = `任务「${task.title}」已确认，正在做准备工作中！`;
        break;
      case 'IN_PROGRESS':
        message = `任务「${task.title}」正在进行中，当前进度 ${task.progress}%`;
        if (task.progressNotes.length > 0) {
          message += `\n最新进展：${task.progressNotes[task.progressNotes.length - 1]}`;
        }
        break;
      case 'BLOCKED':
        const currentBlocker = task.blockers.find(b => !b.isResolved);
        message = `任务「${task.title}」遇到了一点问题：${currentBlocker?.description || '未知困难'}`;
        message += `\n小智正在努力想办法解决！`;
        break;
      case 'RESOLVING':
        message = `任务「${task.title}」遇到的问题正在解决中，已尝试 ${task.blockers.reduce((sum, b) => sum + b.attempts.length, 0)} 种方法`;
        break;
      case 'COMPLETED':
        message = `任务「${task.title}」已完成！\n结果：${task.result}`;
        break;
      default:
        message = `任务「${task.title}」状态：${task.status}`;
    }

    const report: ProgressReport = {
      id: `report_${Date.now()}`,
      generatedAt: new Date(),
      progress: task.progress,
      status: task.status,
      message,
      isAutoGenerated: true,
    };

    task.reports.push(report);
    return report;
  }

  /**
   * 检查并处理所有任务
   */
  private async checkAndProcessTasks(): Promise<void> {
    logger.info('[TaskExecutionTracker] 开始检查任务状态');

    for (const task of this.tasks.values()) {
      if (task.status === 'BLOCKED' || task.status === 'RESOLVING') {
        await this.autoResolveBlocker(task.id);
      }
    }

    logger.info('[TaskExecutionTracker] 任务检查完成');
  }

  /**
   * 自动解决困难
   */
  private async autoResolveBlocker(taskId: string): Promise<void> {
    const task = this.tasks.get(taskId);
    if (!task) return;

    const activeBlocker = task.blockers.find(b => !b.isResolved);
    if (!activeBlocker) return;

    const attempts = activeBlocker.attempts.length;
    
    if (attempts >= this.MAX_BLOCK_ATTEMPTS) {
      // 尝试太多次了，需要向用户求助
      logger.warn({ taskId, attempts }, '任务困难尝试次数过多');
      return;
    }

    // 生成解决方案
    const solutions = this.generateSolutions(activeBlocker.description, task);
    
    for (const solution of solutions) {
      if (attempts + task.solutions.length >= this.MAX_BLOCK_ATTEMPTS) break;
      
      this.attemptSolution(taskId, activeBlocker.id, solution);
      
      // 模拟尝试解决（实际应该调用相关服务）
      await this.simulateSolutionAttempt(taskId, activeBlocker.id, solution);
    }
  }

  /**
   * 生成解决方案
   */
  private generateSolutions(issue: string, task: TaskExecution): string[] {
    const solutions: string[] = [];
    
    // 根据任务类型和遇到的问题生成解决方案
    const taskLower = task.title.toLowerCase();
    const issueLower = issue.toLowerCase();

    // 搜索相关
    if (issueLower.includes('搜索') || issueLower.includes('找')) {
      solutions.push('尝试使用不同的关键词搜索');
      solutions.push('扩大搜索范围');
      solutions.push('使用更精确的筛选条件');
    }

    // 网络相关
    if (issueLower.includes('网络') || issueLower.includes('连接')) {
      solutions.push('检查网络连接状态');
      solutions.push('尝试使用备用网络');
      solutions.push('稍后重试');
    }

    // 权限相关
    if (issueLower.includes('权限') || issueLower.includes('没有权限')) {
      solutions.push('检查账户权限设置');
      solutions.push('申请更高权限');
    }

    // 数据相关
    if (issueLower.includes('数据') || issueLower.includes('获取')) {
      solutions.push('检查数据源是否可用');
      solutions.push('尝试从其他数据源获取');
    }

    // 默认解决方案
    if (solutions.length === 0) {
      solutions.push('重新分析问题');
      solutions.push('搜索相关解决方案');
      solutions.push('尝试分步骤解决');
    }

    return solutions;
  }

  /**
   * 模拟尝试解决
   */
  private async simulateSolutionAttempt(
    taskId: string, 
    blockerId: string, 
    solution: string
  ): Promise<void> {
    // 模拟解决过程
    // 实际应该调用相应的服务来处理
    
    // 假设50%几率解决
    const resolved = Math.random() > 0.5;
    
    if (resolved) {
      this.resolveBlocker(taskId, blockerId, `通过「${solution}」解决了问题`);
      const task = this.tasks.get(taskId);
      if (task && task.status === 'IN_PROGRESS') {
        task.progress = Math.min(90, task.progress + 20);
      }
    } else {
      const task = this.tasks.get(taskId);
      if (task) {
        task.progressNotes.push(`[${new Date().toLocaleString()}] 尝试「${solution}」未成功，继续寻找其他方法...`);
      }
    }
  }

  /**
   * 生成任务总结
   */
  private generateSummary(task: TaskExecution): string {
    let summary = `任务「${task.title}」执行总结：\n\n`;
    
    summary += `📊 执行时长：${this.formatDuration(task.startedAt, task.completedAt)}\n`;
    summary += `📈 完成进度：${task.progress}%\n`;
    
    if (task.blockers.length > 0) {
      const resolved = task.blockers.filter(b => b.isResolved).length;
      summary += `🔧 克服困难：${resolved}/${task.blockers.length} 个\n`;
    }
    
    if (task.progressNotes.length > 0) {
      summary += `\n📝 关键进展：\n`;
      task.progressNotes.slice(-3).forEach(note => {
        summary += `  • ${note}\n`;
      });
    }

    return summary;
  }

  /**
   * 格式化时长
   */
  private formatDuration(start?: Date, end?: Date): string {
    if (!start || !end) return '未知';
    
    const ms = end.getTime() - start.getTime();
    const hours = Math.floor(ms / (1000 * 60 * 60));
    const minutes = Math.floor((ms % (1000 * 60 * 60)) / (1000 * 60));
    
    if (hours > 0) {
      return `${hours}小时${minutes}分钟`;
    }
    return `${minutes}分钟`;
  }

  /**
   * 获取服务状态
   */
  getStatus(): { 
    isRunning: boolean; 
    totalTasks: number;
    activeTasks: number;
    completedTasks: number;
    blockedTasks: number;
  } {
    const allTasks = Array.from(this.tasks.values());
    
    return {
      isRunning: this.isRunning,
      totalTasks: allTasks.length,
      activeTasks: allTasks.filter(t => ['ASSIGNED', 'CONFIRMED', 'IN_PROGRESS', 'BLOCKED', 'RESOLVING'].includes(t.status)).length,
      completedTasks: allTasks.filter(t => t.status === 'COMPLETED').length,
      blockedTasks: allTasks.filter(t => t.status === 'BLOCKED').length,
    };
  }
}

export const taskExecutionTracker = new TaskExecutionTracker();
export default taskExecutionTracker;
