plugins {
    id 'com.android.application'
}

apply plugin: 'kotlin-android'
apply plugin: 'kotlin-kapt'

android {
    namespace "com.xiaozhi.avatar"
    compileSdk rootProject.ext.compileSdkVersion

    defaultConfig {
        applicationId "com.xiaozhi.avatar"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        ndk {
            abiFilters 'arm64-v8a'
        }
    }

    buildFeatures {
        viewBinding true
        buildConfig true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')

    // AndroidX core and UI libraries
    implementation "androidx.appcompat:appcompat:$androidxAppCompatVersion"
    implementation "androidx.core:core-ktx:1.12.0"
    implementation "androidx.coordinatorlayout:coordinatorlayout:1.2.0"

    // Splash screen and biometric auth
    implementation "androidx.core:core-splashscreen:1.0.1"
    implementation "androidx.biometric:biometric:1.1.0"

    implementation project(':capacitor-android')
    testImplementation "junit:junit:$junitVersion"
}
